package org.example.BackEnd.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Users")

public class User {
    @DynamoDBHashKey(attributeName="userid")
    @DynamoDBAutoGeneratedKey
    private String userid;
    @DynamoDBAttribute
    private String nombre;
    @DynamoDBAttribute
    private String username;
    @DynamoDBAttribute
    private String password;

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUserid() {
        return userid;
    }

    public String getNombre() {
        return nombre;
    }


}
