cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: 
      secret-key: 
    dynamodb:
      region: us-east-1
      endpoint: dynamodb.us-east-1.amazonaws.com




